const Apis = {
  formValidator: false,
  formGridDefiner: false,
  formRulesDefiner: false,
  formGroupsDefiner: false,
  iconOptionsDefiner: false,
  tableScrollDefiner: false,
  tableStickyDefiner: false,
  tableSourcesDefiner: false,
  tableSummarysDefiner: false,
  tableColumnsDefiner: false,
  tablePaginateDefiner: false,
  tableLoadDataDefiner: false,
  tableResponserDefiner: false,
  tableEmitSorterDefiner: false,
  tableEmitSelectDefiner: false,
  tableEmitExpandDefiner: false,
  tableEmitPageChangeDefiner: false,
  tableEmitPageSizeChangeDefiner: false,
  tableCustomHeaderRowAttrsDefiner: false,
  tableCustomBodyerRowAttrsDefiner: false,
  tableCustomFooterRowAttrsDefiner: false,
  tableCustomBodyerRowStatesDefiner: false,
  tableCustomHeaderCellRenderDefiner: false,
  tableCustomBodyerCellRenderDefiner: false,
  tableCustomFooterCellRenderDefiner: false,
  treeDataDefiner: false,
  treeLoadDataDefiner: false,
  treeEmitCheckDefiner: false,
  treeEmitSelectDefiner: false,
  treeEmitExpandDefiner: false,
  treeEmitChangeDefiner: false,
  treeDropHandlerDefiner: false,
  treeReplaceFieldsDefiner: false,
}

const Types = {
  SEditCellDatePicker: false,
  SEditCellInput: false,
  SEditCellPanelMode: false,
  SEditCellPickerMode: false,
  SEditCellSelect: false,
  SEditCellSelectOptionType: false,
  SEditCellSelectValueType: false,
  SEditCellTextarea: false,
  SEditCellTreeSelect: false,
  SEditCellTreeSelectOptionType: false,
  SEllipsis: false,
  SForm: false,
  SFormColItem: false,
  SFormColPartItem: false,
  SFormGrid: false,
  SFormGridGutter: false,
  SFormGroupItem: false,
  SFormGroupPartItem: false,
  SFormGroupsDefiner: false,
  SFormNormalizeType: false,
  SFormRowItem: false,
  SFormType: false,
  SFormValidatorManager: false,
  SFormValidatorRule: false,
  SIcon: false,
  SIconSelect: false,
  SIconSelectOption: false,
  STable: false,
  STableBodyerCellRender: false,
  STableCellCacheType: false,
  STableCellFixedType: false,
  STableCellIndexType: false,
  STableCellMegreType: false,
  STableCellSizesType: false,
  STableColumnType: false,
  STableCustomBodyerRowAttrs: false,
  STableCustomBodyerRowStates: false,
  STableCustomFooterRowAttrs: false,
  STableCustomHeaderRowAttrs: false,
  STableExpanderRender: false,
  STableFooterCellRender: false,
  STableHeaderCellRender: false,
  STableKey: false,
  STableLoadSource: false,
  STablePaginateType: false,
  STablePartColumnType: false,
  STablePartPaginate: false,
  STablePartScrollType: false,
  STablePartStickyType: false,
  STablePromiser: false,
  STableRecordType: false,
  STableRefWrapper: false,
  STableRowKey: false,
  STableScrollType: false,
  STableSettingsType: false,
  STableSize: false,
  STableSorterType: false,
  STableStickyType: false,
  STableTreeKey: false,
  STableValuer: false,
  STableWrapColumnType: false,
  STableWrapRecordType: false,
  STree: false,
  STreeCacher: false,
  STreeDropHandler: false,
  STreeEmiterCheck: false,
  STreeEmiterChange: false,
  STreeEmiterExpand: false,
  STreeEmiterSelect: false,
  STreeEventDragstart: false,
  STreeEventDrop: false,
  STreeFieldNames: false,
  STreeFilterProps: false,
  STreeKey: false,
  STreeKeys: false,
  STreeLoadData: false,
  STreeMethoder: false,
  STreePartSourceNode: false,
  STreePartTargetNode: false,
  STreeSourceNode: false,
  STreeSourceNodes: false,
  STreeSourcer: false,
  STreeSpreadNodes: false,
  STreeStater: false,
  STreeTargeter: false,
  STreeTargetNode: false,
  STreeTargetNodes: false,
  STreeTransformer: false,
}

export default [
  {
    languageOptions: {
      globals: {
        ...Apis,
        ...Types,
      },
    },
  },
]
